services:
  accounts:
    image: vabhav276/demo-bank-accounts:0.1.0
    container_name: accounts-service
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - demo-bank
  cards:
    image: vabhav276/demo-bank-cards:0.1.0
    container_name: cards-service
    ports:
      - "8090:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - demo-bank
  loans:
    image: vabhav276/demo-bank-loans:0.1.0
    container_name: loans-service
    ports:
      - "9000:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - demo-bank
networks:
  demo-bank:
    driver: "bridge"