spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"
contact:
  message: "Welcome to Demo bank loans related prod APIs "
  contactDetails:
    name: "Reine Aishwarya - Product Owner"
    email: "aishwarya@demobank.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384